[webservers]
172.17.6.159 ansible_become_password=admin
172.17.6.161 ansible_become_password=admin

[dbservers]

[dbservers]
172.17.6.171 ansible_user=user ansible_password=admin ansible_become_password=admin
